  
on:
  push:

jobs:

  build:
    strategy:
      fail-fast: false
      matrix:
        size: [1, 1024, $((1024*1024)), $((2*1024*1024)), $((4*1024*1024)), $((8*1024*1024)), $((10*1024*1024)), $((16*1024*1024)), $((32*1024*1024)), $((64*1024*1024))]
      
    runs-on: ubuntu-latest

    env:
      REGISTRY: docker.pkg.github.com
      IMAGE: $REGISTRY/${{ github.repository }}/docker-large-images-test

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ${{ env.IMAGE }} --build-arg SIZE=${{ matrix.size }}

    - run: docker login https://$REGISTRY -u token -p ${{ github.token }}
    - name: Push the image
      run: docker push ${{ env.IMAGE }}
